### PR TITLE
Fixes race condition on self.conn, and fixes bug with infinite reconnect

### PR DESCRIPTION
**Pull request by tomponline**
* When restarting Freeswitch with fsock compiled with race condition detection, this was causing a crash
* Infinite reconnects not working

### CODE REVIEW

**Comment by tomponline** [comment]
@danbogos are you happy for this to be merged? Thanks

**Comment by danbogos** [comment]
@tomponline thanks for this. Will improve it in a next commit but I appreciate your point.

DanB

**Comment by danbogos** [comment]
@tomponline is there any chance you send me the output detected by the race detector? For some reason I cannot figure out the exact point it produces the race.

Ta,
DanB

**Comment by tomponline** [comment]
@danbogos yes I'll get the error message I was getting...it was when I restarted freeswitch

**Comment by tomponline** [comment]
@danbogos 

```
Apr 24 21:02:21 tpel6 python: fsqueue WARNING: DATA RACE
Apr 24 21:02:21 tpel6 python: fsqueue Write by goroutine 69:
Apr 24 21:02:21 tpel6 python: fsqueue   github.com/cgrates/fsock.(*FSock).Disconnect()
Apr 24 21:02:21 tpel6 python: fsqueue       /home/sites/go/src/github.com/tomponline/ict-fshandler/Godeps/_workspace/src/github.com/cgrates/fsock/fsock.go:406 +0x108
Apr 24 21:02:21 tpel6 python: fsqueue   github.com/cgrates/fsock.(*FSock).readHeaders()
Apr 24 21:02:21 tpel6 python: fsqueue       /home/sites/go/src/github.com/tomponline/ict-fshandler/Godeps/_workspace/src/github.com/cgrates/fsock/fsock.go:227 +0x2c5
Apr 24 21:02:21 tpel6 python: fsqueue   github.com/cgrates/fsock.(*FSock).readEvent()
Apr 24 21:02:21 tpel6 python: fsqueue       /home/sites/go/src/github.com/tomponline/ict-fshandler/Godeps/_workspace/src/github.com/cgrates/fsock/fsock.go:262 +0xcb
Apr 24 21:02:21 tpel6 fsqueue[31730]: <FSock> Attempt to connect to FreeSWITCH, received: dial tcp 127.0.0.1:8021: connection refused
Apr 24 21:02:21 tpel6 python: fsqueue   github.com/cgrates/fsock.(*FSock).readEvents()
Apr 24 21:02:21 tpel6 python: fsqueue       /home/sites/go/src/github.com/tomponline/ict-fshandler/Godeps/_workspace/src/github.com/cgrates/fsock/fsock.go:287 +0x7d
Apr 24 21:02:21 tpel6 python: fsqueue 
Apr 24 21:02:21 tpel6 python: fsqueue Previous read by goroutine 6:
Apr 24 21:02:21 tpel6 python: fsqueue   github.com/cgrates/fsock.(*FSock).ReconnectIfNeeded()
Apr 24 21:02:21 tpel6 python: fsqueue       /home/sites/go/src/github.com/tomponline/ict-fshandler/Godeps/_workspace/src/github.com/cgrates/fsock/fsock.go:470 +0x19e
Apr 24 21:02:21 tpel6 python: fsqueue   github.com/cgrates/fsock.(*FSock).ReadEvents()
Apr 24 21:02:21 tpel6 python: fsqueue       /home/sites/go/src/github.com/tomponline/ict-fshandler/Godeps/_workspace/src/github.com/cgrates/fsock/fsock.go:514 +0x123
Apr 24 21:02:21 tpel6 python: fsqueue 
Apr 24 21:02:21 tpel6 python: fsqueue Goroutine 69 (running) created at:
Apr 24 21:02:21 tpel6 python: fsqueue   github.com/cgrates/fsock.(*FSock).Connect()
Apr 24 21:02:21 tpel6 python: fsqueue       /home/sites/go/src/github.com/tomponline/ict-fshandler/Godeps/_workspace/src/github.com/cgrates/fsock/fsock.go:454 +0x88c
Apr 24 21:02:21 tpel6 python: fsqueue   github.com/cgrates/fsock.(*FSock).ReconnectIfNeeded()
Apr 24 21:02:21 tpel6 python: fsqueue       /home/sites/go/src/github.com/tomponline/ict-fshandler/Godeps/_workspace/src/github.com/cgrates/fsock/fsock.go:465 +0xee
Apr 24 21:02:21 tpel6 python: fsqueue   github.com/cgrates/fsock.(*FSock).ReadEvents()
Apr 24 21:02:21 tpel6 python: fsqueue       /home/sites/go/src/github.com/tomponline/ict-fshandler/Godeps/_workspace/src/github.com/cgrates/fsock/fsock.go:514 +0x123
Apr 24 21:02:21 tpel6 python: fsqueue 
Apr 24 21:02:21 tpel6 python: fsqueue Goroutine 6 (running) created at:
Apr 24 21:02:21 tpel6 python: fsqueue   main.main()
Apr 24 21:02:21 tpel6 python: fsqueue       /home/sites/go/src/github.com/tomponline/ict-fshandler/fsqueue/fsqueue.go:63 +0x6e3
```

**Comment by danbogos** [comment]
Great, thanks. Have updated also the code with proper locks (global ones are locking also other connections from the pool).

Cheers,
DanB

**Pull request merged**
